server:
  port: 1003
spring:
  application:
    name: portal-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

feign:
  hystrix:
    enabled: false

# ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

# zuul
zuul:
  routes:
    user:
      path: /api-user/**
      service-id: user-service
